### ISSUE TITLE
[Feat] Suggestions on imporving repo

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [bhagatpratham/notes-app#1]
Hey, thanks for sharing your project. It's awesome. These are few suggestions from my side.
1. Remove Unnecessary sections which are not in use
<img src="https://i.imgur.com/qFzriss.png">
2. Add a description of the project
<img src="https://i.imgur.com/8aiw4bv.png">
3. Add important documents to the project
<img src="https://i.imgur.com/fzg8miA.png">
4. Add screenshots (or maybe gif to the readme)

**Comment by bhagatpratham** [comment]
Thank you for suggestions,
I will start working on this soon
